version: '2'
services:
  jhipstertest8-app:
    image: jhipstertest8
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertest8-postgresql:5432/jhipstertest8
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstertest8-postgresql:
    extends:
      file: postgresql.yml
      service: jhipstertest8-postgresql
