version: '2'
services:
  jhipstertest8-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/jhipstertest8/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipstertest8
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
